name = "DemoPlots"
uuid = "1f342d77-e470-4fee-b19c-8e8d164daffc"
authors = ["Tommaso Stentella <stentell@molgen.mpg.de> and contributors"]
version = "0.4.4"

[deps]
DemoInfer = "50651ce3-0423-45d2-b99c-8ea4267d2717"
HistogramBinnings = "8296b526-8b84-45d3-81d6-36727ca56808"
MLDs = "cac4bed1-6c8c-4dbe-be0d-c63a427c1233"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.10"
DemoInfer = "0.4.3"
HistogramBinnings = "0.1.1"
MLDs = "0.1.4"
PyCall = "1.96.4"
PyPlot = "2.11.6"
StatsBase = "0.34.5"